### PR TITLE
fix: amount inputs work with locales that use comma separators

### LINKED ISSUE #630: Can't add price with cents/fractions
Steps to reproduce

1. Edit price of a variant
2. Type in fractional price, in example 19,50
3. After saving see the price rounded down to 19

Price is saved in database as 1900, should be 1950.

### PR DESCRIPTION
**Pull request by kasperkristensen**
**What**

- Fixes a bug where cents/fractions were ignored when using the admin dashboard in a browser with a locale that uses commas as the decimal separator.

**How**
- Instead of using `parseFloat` to get the value that should be used to calculate the persisted amount, we instead use the float that is returned as part of the `onChange` function in react-currency-input-field.

Closes #630 

Closes CORE-595

### CODE REVIEW

File: src/components/organisms/currency-input/index.tsx [hunk 1]
```diff
@@ -189,48 +189,78 @@ const Amount = forwardRef<HTMLInputElement, AmountInputProps>(
...
+    //     value = 0
+    //   }
+
+    //   if (currencyInfo) {
+    //     const amount = parseFloat(value)
+    //     const multiplier = getDecimalDigits(currencyInfo.code)
+    //     persistedAmount = multiplier * amount
+    //   }
+
+    //   if (onChange && typeof persistedAmount !== "undefined") {
```
Comment (srindom) [inline src/components/organisms/currency-input/index.tsx:209]: todo: remove

**Review by srindom — APPROVED** [review]
LGTM!
